### ISSUE TITLE
tree里的value如何只保存tree的key而不继续遍历后面的blob呢？

### ISSUE THREAD

**Issue by yiningma1001** [zhenmin26/version-control-system#6]
感觉文件都显示的话有点多，需不需要是保留到tree的层面呢？

**Comment by js00070** [comment]
没懂是什么意思，为什么要只保留tree的key不遍历blob？

**Comment by yiningma1001** [comment]
> 没懂是什么意思，为什么要只保留tree的key不遍历blob？

嗯，谢谢学长，是我对递归理解有点问题，现在明白了。
